"""auto-vote

Revision ID: f3d9fe8c4cfb
Revises: 6eee1ec6b06a
Create Date: 2023-02-06 20:42:38.418591

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f3d9fe8c4cfb"
down_revision = "6eee1ec6b06a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.add_column("posts", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.drop_constraint("posts_users_fk", "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_users_fk", "posts", "users", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("posts", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint("posts_users_fk", "posts", type_="foreignkey")
    op.create_foreign_key(
        "posts_users_fk", "posts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("posts", "owner_id")
    op.drop_table("votes")
    # ### end Alembic commands ###
